[package]
name = "aterms"
version = "0.1.0"
authors = ["Matthijs Bijman <matthijs@bijman.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aterms"

[dependencies]
nom = "6.0.0"
indenter = "0.2"